name: C/C++ CI (Alpine i386)
on:
  workflow_dispatch:
jobs:
  build-alpine-i386:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build and test on Alpine i386
      uses: docker://i386/alpine:latest
      with:
        entrypoint: /bin/sh
        args: |
          -c "
          apk add --no-cache build-base autoconf automake libtool &&
          autoreconf -ivf &&
          ./configure &&
          make &&
          make check
          "